### ISSUE TITLE
Consider support for openbsd HVM as netvm

### ISSUE THREAD

**Issue by Szewcson** [mirage/qubes-mirage-firewall#146] opened 2022-09-12 11:04 UTC
On Qubes forum  (https://forum.qubes-os.org/t/unable-to-shutdown-mirage-firewall-without-netvm-attached/13606) some users reporting problems with mieage-firewall that not have netvm attached. Since it is not a normal use case it is the right configuration when using openbsd as netvm (https://github.com/jcholsap/freemod/issues/1). Maybe adding support (fixing this issue and providing trustworthy script for configuring routing in that case) is worth considering.

**Comment by palainp** [comment] 2022-09-12 12:22
Hi, thanks for this report.
If I understand correctly, openbsd's netvm must specifically set the netvm to "none" for mirage-fw. When I try to start mirage-fw with netvm set to "none", I get the following result in the log:
```
...
[2022-09-12 13:29:33] 2022-09-12 11:29:33 -00:00: WRN [dao] QubesDB key "/qubes-ip" not (yet) present; waiting for QubesDB to change...
...
```
but mirage-fw starts correctly.

The message is written by https://github.com/mirage/qubes-mirage-firewall/blob/2af63f1f45338cc3c160dd453d8473a182bc7d8b/dao.ml#L153 which is called in https://github.com/mirage/qubes-mirage-firewall/blob/2af63f1f45338cc3c160dd453d8473a182bc7d8b/unikernel.ml#L69

To me it's probably doable to add options to manually configure the IP, gateway IP, and DNS IP(s) instead of reading qubesDB (but both cases should be mutually exclusive). And the script linked in the issue seems to only route all traffic to the gateway with NAT (more complicated scripts may not be easy to write here, and writing a shell interpreter will be out of scope IMO).

**Comment by Szewcson** [comment] 2022-09-12 13:01
I don't fully understand what is needed to create this setup yet, since I'm not trying it myself. As I understand problem is that there is no qubes-agents for bsd so the configuration should be manual. I think that adding the option to set those parameters manually and enable this kind of routing should be enough. Since for disposables there was proposed some solution inside bsd: https://forum.qubes-os.org/t/configuring-networking-in-openbsd-hvm/441/6

**Comment by Szewcson** [comment] 2022-09-12 18:45
I see that even VM without net qube has active firewall settings. So maybe it is possible to use it like in normal use case. So I think that main difference will using manually set addressees.

**Comment by palainp** [comment] 2022-09-15 18:32
hmm, I added some command line options to set the ip/gw/dns configuration if qubesDB does not provide anything (keys are missing), but it now fails to read with xenstore. The issue is that netvm won't be started before mirage-fw and has no network connection (as a client in the current naming) during the startup stage.

It will need a rewrite on how uplink is used. To go further, I would have to configure a netvm openbsd HVM which will take me some times ;)

**Comment by Szewcson** [comment] 2022-09-16 06:46
Configuring netvm according to those guides is rather simple task if You have knowladge about networks (for me that part was the hardest since I have a little experience with that topic). There is a hint in the topic I posted that when You are using dvm as "netvm" (a firewall but since OpenBSD not have netback driver we are connecting using netfront) You should add additional line in hosntame.xnf0 for cloning interface to other subnet. But You can encounter problems with drivers (as I did - none of my NICs not working on OpenBSD when passed through).

**Comment by resulin** [comment] 2023-06-29 14:46
@palainp would you have some time for this? I think it would be a great feature for the next release. I followed the linked guide in https://github.com/jcholsap/freemod/issues/1 and found it to be straightforward enough.

**Comment by palainp** [comment] 2023-06-30 15:23
Hi @resulin, thanks for updating the status of this issue!
I managed to try it out again this afternoon (still no OpenBSD, but a linux sys-net configured to default route to a WiFi gw, this sounds very similar to what the tutorial says) and it seems I've done a step beyond :) (alas no deep testing so far).

If you and/or @Szewcson have some free time, would you mind to try out to compile and run https://github.com/palainp/qubes-mirage-firewall/tree/common-vif ?

You'll also have to set some new properties to the unikernel:
```
qvm-prefs --set mirage-firewall -- kernelopts '--ipv4=X.X.X.X --ipv4-gw=Y.Y.Y.Y'
```
with X.X.X.X the IP address for mirage-firewall and Y.Y.Y.Y the IP address of your OpenBSD HVM.

**Comment by palainp** [comment] 2023-06-30 15:56
Sorry, spoken too fast. I still have some reworking to do :(

**Comment by palainp** [comment] 2023-07-01 15:27
Update: my openbsd VM seems to be unable to configure my wireless adapter correctly (kernel panic :( ) and I haven't any wired connexion for some times, so I can't test further with openbsd but my linux sys-net is receiving AppVM packets through qubes-mirage (this seems to be what the sys-firewall script does) in the following setup: `sys-net -> mirage-fw <- AppVM` (with the arrow standing for the netvm property).

I'm going to have some housekeeping in the code before a release ready version, but it seems ok for testing purpose now. @resulin are you ok for trying out that version (I updated the hashsum for docker which should match your build artifact, this is the easiest way to compile the unikernel)?

**Comment by resulin** [comment] 2023-07-01 19:20
Thanks for the quick intervention @palainp! I will try to find some time to try all of this as soon as possible.
------- Original Message -------

**Comment by resulin** [comment] 2023-07-02 14:49
Downloaded and compiled your branch and got it working with hash:
sha256sum vmlinuz
1f621d3bde2cf2905b5ad333f7dbde9ef99479251118e1a1da9b4da15957a87d vmlinuz
But I keep hitting an error while setting up ethernet on the openbsd vm, I opened a forum thread to see if I can get any help, hopefully after it will work smoothly with the new mirage-firewall image
https://forum.qubes-os.org/t/help-in-setting-up-openbsd-as-a-netvm-alongside-mirage-firewall/19618

------- Original Message -------

**Comment by palainp** [comment] 2023-07-02 16:33
That's great!
I hope you'll manage to get networking with openBSD :) (and also don't forget to set `kernelopts` to the fw IP and gw to openBSD IP `qvm-prefs --set mirage-firewall -- kernelopts '--ipv4=X.X.X.X --ipv4-gw=Y.Y.Y.Y'`).

**Closed** 2024-04-24 09:49 UTC
