### ISSUE TITLE
Qubes R4.1

### ISSUE THREAD

**Issue by bluesteal** [mirage/qubes-mirage-firewall#173] opened 2023-03-30 02:31 UTC
Does the following tutorial apply to Qubes R4.1?

https://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/#the-xen-virtual-network-layer

I don't see a "Proxy-VM" option in that version of Qubes.

Also, there is no option to set the kernel to 'mirage-firewall'

**Comment by bluesteal** [comment] 2023-03-30 05:27
ok it works now; the only thing needed is to get the qubes libraries installed (GUI, qrexec, qubesDB)

**Comment by palainp** [comment] 2023-04-02 08:40
Thanks for your questions. You'd follow the README instructions for newer Qubes. It should works for Qubes 4.1.

> ok it works now;

Does that statement is relevant in #172 and should close it?

> the only thing needed is to get the qubes libraries installed (GUI, qrexec, qubesDB)

Those are directly included in the unikernel during the compilation. You can check the fw logs in dom0, you should be able to see that qrexec v3 is used and Fw rules are updated (that would mean that qrexec and qubesDB are correctly "installed"). GUI was removed a couple of month ago.

**Comment by bluesteal** [comment] 2023-04-02 20:07
Thanks for your response. Can you link me for the README? and how can I check fw rules in dom0?

**Comment by hannesm** [comment] 2023-04-03 08:38
The README of this repository includes a section about how to deploy it: https://github.com/mirage/qubes-mirage-firewall#deploy

"How can I check fw rules in dom0" -- In dom0 you have the Qubes Manager that can display (and edit) firewall rules, see https://www.qubes-os.org/doc/firewall/ -- these rules are used by the qubes mirage firewall.

**Comment by palainp** [comment] 2023-04-03 09:30
Thanks @hannesm, and @bluesteal can check the vm logs as well reading the file `/var/log/xen/console/guest-mirage-fw.log` with `mirage-fw` the name of your mirage unikernel AppVM.
You should find some information like:
```
Solo5: Xen console: port 0x2, ring @0x00000000FEFFF000
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Bindings version v0.7.3
Solo5: Memory map: 32 MB addressable:
Solo5:   reserved @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x319fff)
Solo5:     rodata @ (0x31a000 - 0x384fff)
Solo5:       data @ (0x385000 - 0x53ffff)
Solo5:       heap >= 0x540000 < stack < 0x2000000
...
INF [qubes.db] got update: "/qubes-iptables-header" = "# Generated by Qubes Core on XXXX 2023\n*filter\n:INPUT DROP [0:0]\n:FORWARD DROP [0:0]\n:OUTPUT ACCEPT [0:0]\n-A INPUT -i vif+ -p udp -m udp --dport 68 -j DROP\n-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n-A INPUT -p icmp -j ACCEPT\n-A INPUT -i lo -j ACCEPT\n-A INPUT -j REJECT --reject-with icmp-host-prohibited\n-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n-A FORWARD -i vif+ -o vif+ -j DROP\nCOMMIT\n"
INF [qubes.db] got update: "/qubes-iptables-domainrules/6" = "*filter\n-A FORWARD -s 10.137.0.XX -j ACCEPT\n-A FORWARD -s 10.137.0.XX -j DROP\nCOMMIT\n"
INF [qubes.db] got update: "/qubes-iptables" = "reload"
INF [qubes.db] got update: "/connected-ips" = "10.137.0.YY ..."
INF [qubes.db] got update: "/connected-ips6" = ""
...
```

**Comment by bluesteal** [comment] 2023-04-03 23:49
Which method do you recommend when deploying the unikernel? Should it be downloaded from 

https://github.com/mirage/qubes-mirage-firewall/releases/download/v0.8.4/mirage-firewall.tar.bz2

into dom0? or is the best way to build it from source using docker on a separate AppVM?

**Comment by bluesteal** [comment] 2023-04-03 23:53
I have recently tried to download from the above link into dom0, but received an error message:

bzip2: (stdin) is not a bzip2 file
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by hannesm** [comment] 2023-04-04 06:38
> Which method do you recommend when deploying the unikernel? Should it be downloaded from
> 
> https://github.com/mirage/qubes-mirage-firewall/releases/download/v0.8.4/mirage-firewall.tar.bz2
> 
> into dom0? 

That is the recommend path to take, downloading and unpacking.

> or is the best way to build it from source using docker on a separate AppVM?

Since it is a reproducible build, you can as well do that and will get the very same binary.

> bzip2: (stdin) is not a bzip2 file
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now

Strange, I just downloaded that tarball, and both `tar tf` and `bunzip2` are fine with it. Would you mind to paste the exact commands you used, and the `sha256sum` of the tarball you downloaded (for me, it is 2c985671a5620f395d1cc40f7f505660fd1e07bcaaaf77f698ce13f76f47cc20, and its size is  1404471 bytes)?

**Comment by bluesteal** [comment] 2023-04-04 23:34
qvm-run -p sys-net 'wget -o - https://github.com/mirage/qubes-mirage-firewall/releases/download/v0.8.4/mireage-firewall.tar.bz2' > mirage-firewall.tar.bz2

**Comment by bluesteal** [comment] 2023-04-04 23:36
tar tf mirage-firewall.tar.bz2

**Comment by palainp** [comment] 2023-04-05 05:15
Please follow the deploy procedure (https://github.com/mirage/qubes-mirage-firewall#deploy):
- download the archive in domU
- untar it there (not in dom0, see https://github.com/mirage/qubes-mirage-firewall/issues/84#issue-529473022)
- after that copy the unikernel into dom0 with qvm-run as described.
And as a side note, sys-net, as a really exposed AppVM, may be one of the least trusted AppVM for downloading the archive, you should prefer another AppvM for that task.

**Comment by bluesteal** [comment] 2023-04-05 05:19
how to copy the archive into dom0?

**Comment by palainp** [comment] 2023-04-05 06:05
As described in the deploy section in dom0  `qvm-run -p dev 'cat mirage-firewall/vmlinuz' > vmlinuz` :)

**Comment by bluesteal** [comment] 2023-04-06 03:13
ok it appears to be up and running

**Comment by 100111001** [comment] 2023-04-07 08:55
@palainp If you are interested in making installation and deployment easier or to offer a scripted installation, here are 2 scripts for that::

Saltstack (feel free to use this in our repo):
https://gist.github.com/100111001/4eca0f78ed69d597d562a1515168fa6c

Bash:
https://github.com/one7two99/my-qubes/tree/master/mirage-firewall

**Comment by palainp** [comment] 2023-04-07 09:38
Hi @100111001 this looks great, unfortunately I don't have time to look into it right now, but I think it would be a good improvement!

I just have a minor comment because the hashsum doesn't seem to be validated (as commented in the bash version "I hope that the Qubes Team or the mirage-firewall project will provide fingerprints to verify the binary" by @one7two99).
This won't be perfect because you have to download and trust a second file on the same platform (which can therefore be modified like the unikernel), but it might be interesting to check the sha256sum against the one in `build-with-docker.sh` with something like (the sum in the docker script should always be updated on releases):
```
diff <(curl -s https://raw.githubusercontent.com/mirage/qubes-mirage-firewall/main/build-with-docker.sh | grep "SHA2 last known:" |cut -d' ' -f5 | tr -d \") <(sha256sum ~/mirage-firewall/vmlinuz | cut -d' ' -f1) && echo "OK" || echo "KO"
```
Do you think some similar check can be implemented (I don't know the salt syntax/possibilities)?

It would also be interesting to use as well the ROBUR reproducible platform (https://builds.robur.coop/job/qubes-firewall) which continuously builds and provides qubes-mirage-firewall (among other unikernels) with an updated mirage ecosystem (that's why the sha256sum is the one from `2022-12-18 20:03:45Z`, the latest versions use updated mirage libraries).

**Comment by 100111001** [comment] 2023-04-07 16:52
Done. Script is updated to compare the checksum from the latest docker build.

Is the latest docker build = latest release? Otherwise the checksum comparison will be fail.

Regarding ROBUR, is there a way to link the binary from latest github release to one of those builds? By using a tag? If that's the case, I'm happy to update the script to use the source from ROBUR.

**Comment by hannesm** [comment] 2023-04-08 15:42
> is there a way to link the binary from latest github release to one of those builds?

You can search for the hash -- i.e. https://builds.robur.coop/hash?sha256=55a2f823d66473c7d0be66a93289d48b6557f18c9257c6f98aa5a4583663d3c2 and will receive one of the builds that matches the checksum :)
So, https://builds.robur.coop/job/qubes-firewall/build/ea3ccecd-e883-489d-ba4a-c869d8731b08 is a reproducible build of the qubes-mirage-firewall. (Which lists a bunch of other builds with different input (i.e. dependencies) that result in the same binary).

> By using a tag?

We have that planned. But keep in mind that a specific qubes-mirage-firewall commit (i.e. tag) may lead to different binaries, depending on its dependencies and system packages.

**Comment by palainp** [comment] 2023-07-06 09:33
I think the opening issue is now solved.
@100111001 your salt script should still work with the new release, if so, would you mind to open a PR to add the installation script in the repository?

**Comment by 100111001** [comment] 2023-08-17 22:51
@palainp done: https://github.com/mirage/qubes-mirage-firewall/pull/179

**Comment by palainp** [comment] 2023-08-18 10:56
Thanks you!

**Closed by palainp** 2023-08-18 10:56 UTC
